# Generated by Django 4.2.4 on 2023-09-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_preparation_unit_recipe_servings_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
